version: "3.7"
services:
  traefik:
    image: containous/traefik:experimental-master
    container_name: traefik
    restart: always
    networks:
      vpn:
      default:
    extra_hosts: 
      - host.docker.internal:172.17.0.1
    command:
      - --api.insecure=true
      - --providers.docker=true
      - --providers.file.directory=/etc/traefik
      - --providers.file.filename=config.toml
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --certificatesresolvers.mydnschallenge.acme.dnschallenge=true
      - --certificatesresolvers.myresolver.acme.httpChallenge=true
      - --certificatesresolvers.mydnschallenge.acme.dnschallenge.provider=cloudflare
      - --certificatesResolvers.myresolver.acme.httpChallenge.entryPoint=websecure
      - --certificatesresolvers.mydnschallenge.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory
      - --certificatesresolvers.mydnschallenge.acme.email=${CF_EMAIL}
      - --certificatesresolvers.myresolver.acme.email=${CF_EMAIL}
      - --certificatesresolvers.mydnschallenge.acme.storage=/letsencrypt/acme.json
      - --certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    environment:
      - CF_API_EMAIL=${CF_EMAIL}
      - CF_API_KEY=${CF_API_KEY}
    volumes:
      - ${HOME}/Docker/traefik/.letsencrypt:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${HOME}/Docker/traefik:/etc/traefik
  nginx-personal:
    image: linuxserver/nginx
    container_name: my-web-nginx
    depends_on: 
      - traefik    
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${HOME}/Docker/ANTHONYRABBITO/config:/config
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.myweb.rule=${DOMAIN}
      - traefik.http.routers.myweb.entrypoints=websecure
      - traefik.http.routers.myweb.tls.certresolver=mydnschallenge
      - traefik.http.services.myweb.loadbalancer.server.port=80
  bitwarden:
    image: bitwardenrs/server
    restart: unless-stopped
    container_name: bitwarden-rs
    depends_on: 
      - traefik
    volumes:
      - ${HOME}/Docker/bitwarden:/data
    environment:
      - WEBSOCKET_ENABLED= true
      - SIGNUPS_ALLOWED= false
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}      
    labels:
      - traefik.enable=true
      - traefik.http.middlewares.redirect-https.redirectScheme.scheme=https
      - traefik.http.middlewares.redirect-https.redirectScheme.permanent=true
      - traefik.http.routers.bitwarden-ui-https.rule=${BWDOMAIN}
      - traefik.http.routers.bitwarden-ui-https.entrypoints=websecure
      - traefik.http.routers.bitwarden-ui-https.tls=true
      - traefik.http.routers.bitwarden-ui-https.service=bitwarden-ui
      - traefik.http.routers.bitwarden-ui-http.rule=${BWDOMAIN}
      - traefik.http.routers.bitwarden-ui-http.entrypoints=web
      - traefik.http.routers.bitwarden-ui-http.middlewares=redirect-https
      - traefik.http.routers.bitwarden-ui-http.service=bitwarden-ui
      - traefik.http.services.bitwarden-ui.loadbalancer.server.port=80
      - traefik.http.routers.bitwarden-websocket-https.rule=${BWDOMAIN_WS}
      - traefik.http.routers.bitwarden-websocket-https.entrypoints=websecure
      - traefik.http.routers.bitwarden-websocket-https.tls=true
      - traefik.http.routers.bitwarden-websocket-https.service=bitwarden-websocket
      - traefik.http.routers.bitwarden-websocket-http.rule=${BWDOMAIN_WS}
      - traefik.http.routers.bitwarden-websocket-http.entrypoints=web
      - traefik.http.routers.bitwarden-websocket-http.middlewares=redirect-https
      - traefik.http.routers.bitwarden-websocket-http.service=bitwarden-websocket
      - traefik.http.services.bitwarden-websocket.loadbalancer.server.port=3012
  cloudflare-ddns:
    image: oznu/cloudflare-ddns:latest
    container_name: cloudflare-dynDNS
    restart: always  
    environment:
      - EMAIL=${CF_EMAIL}
      - API_KEY=${CF_API_KEY}
      - ZONE=${CF_BASE}
      - SUBDOMAIN=${SUBDOMAIN}
      - PROXIED=false
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
  homeassistant:
    container_name: homeassistant-stable
    image: homeassistant/home-assistant:stable
    volumes:
      - ${HOME}/Docker/homeassistant:/config
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
      - /dev/ttyUSB1:/dev/ttyUSB1
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.homeassistant.rule=${HILLHADOMAIN}
      - traefik.http.routers.homeassistant.entrypoints=websecure
      - traefik.http.routers.homeassistant.tls.certresolver=mydnschallenge
      - traefik.http.services.homeassistant.loadbalancer.server.port=8123
  nodered:
    container_name: node-red
    restart: unless-stopped
    image: nodered/node-red:latest
    depends_on:
      - homeassistant
      - traefik
    user: root
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
    volumes:
      - ${HOME}/Docker/nodered:/data
      - /etc/localtime:/etc/localtime:ro
    labels:
      - traefik.enable=true
      - traefik.http.routers.nodered.rule=Host(`node-red.hill`)
      - traefik.http.routers.nodered.entrypoints=web
  filebrowser:
    image: halverneus/static-file-server
    container_name: fileserver-web
    depends_on: 
      - traefik
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    restart: unless-stopped
    volumes:
      - /mnt/zfs/Docker/fileserve:/web
    labels:
      - traefik.enable=true
      - traefik.http.routers.fileserve.rule=${FS_NOHAT}
      - traefik.http.routers.fileserve.entrypoints=websecure
      - traefik.http.routers.fileserve.tls.certresolver=mydnschallenge
      - traefik.http.services.fileserve.loadbalancer.server.port=8080
  thecap:
    image: linuxserver/nginx
    container_name: cap-web-nginx
    depends_on: 
      - traefik
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${HOME}/Docker/cap/config:/config
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.cap.rule=${CAP}
      - traefik.http.routers.cap.entrypoints=websecure
      - traefik.http.routers.cap.tls.certresolver=mydnschallenge
      - traefik.http.services.cap.loadbalancer.server.port=80
  samba:
    image: dperson/samba
    container_name: samba
    environment:
      - TZ:=${TZ}
      - USERID=${PUID}
      - GROUPID=${PUID}
      - PUID=${PUID}
      - PGID=${PGID}
    network_mode: host
    read_only: true
    tmpfs:
      - /tmp
    restart: unless-stopped
    stdin_open: true
    tty: true
    volumes:
      - /mnt/zfs/Storage/Emulation/:/mnt
    command: ${SAMBACMD}
  nginx:
    image: linuxserver/nginx
    container_name: njco-web-nginx
    depends_on: 
      - traefik
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${HOME}/Docker/NJCO/config:/config
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.njco.rule=${NJCO}
      - traefik.http.routers.njco.entrypoints=websecure
      - traefik.http.routers.njco.tls.certresolver=mydnschallenge    
      - traefik.http.services.njco.loadbalancer.server.port=80
  plex:
    image: linuxserver/plex
    container_name: plex-pms
    tmpfs:
      - /tmp
    network_mode: host
    environment:
      - PUID${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - VERSION=latest
      - UMASK_SET=022
    volumes:
      - ${HOME}/Docker/plex/library:/config
      - /mnt/zfs/Storage/Media/TV:/tv
      - /mnt/zfs/Storage/Media/Movies:/movies
      - /mnt/zfs/Storage/Media/Music:/music
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.plex.rule=${PLEXHOST}
      - traefik.http.routers.plex.entrypoints=websecure
      - traefik.http.routers.plex.tls.certresolver=mydnschallenge
      - traefik.http.services.plex.loadbalancer.server.port=32400
      - traefik.http.routers.plex-internal.rule=Host(`plex.hill`)
      - traefik.http.routers.plex-internal.entrypoints=web
  deluge:
    image: linuxserver/deluge
    container_name: deluge
    networks:
      vpn:
    environment:
      - PUID${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - UMASK_SET=022
      - DELUGE_LOGLEVEL=error
    volumes:
      - ${HOME}/Docker/plex/deluge:/config
      - /mnt/zfs/Docker/pms/delugeDownloads:/downloads
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.services.deluge.loadbalancer.server.port=8112
      - traefik.http.routers.deluge.rule=Host(`deluge.hill`)
      - traefik.http.routers.deluge.entrypoints=web
  jackett:
    image: linuxserver/jackett
    container_name: jackett
    environment:
      - PUID=${PUID}
      - PGID={PGID}
      - TZ=${TZ}
    volumes:
      - ${HOME}/Docker/plex/jackett:/config
      - /mnt/zfs/Docker/pms/delugeDownloads:/downloads
    labels:
      - traefik.enable=true
      - traefik.http.services.jackett.loadbalancer.server.port=9117
      - traefik.http.routers.jackett.rule=Host(`jackett.hill`)
      - traefik.http.routers.jackett.entrypoints=web
  sonarr:
    image: linuxserver/sonarr:latest
    container_name: sonarr
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${HOME}/Docker/plex/sonarr:/config
      - /mnt/zfs/Storage/Media/TV/:/tv
      - /mnt/zfs/Docker/pms/delugeDownloads:/data
      - /mnt/zfs/Docker/pms/nzbget/downloads/completed/TV:/downloads/completed/TV
      - /mnt/zfs/Docker/pms/nzbget/downloads/intermediate:/downloads/intermediate
    labels:
      - traefik.enable=true
      - traefik.http.services.sonarr.loadbalancer.server.port=8989
      - traefik.http.routers.sonarr.rule=Host(`sonarr.hill`)
      - traefik.http.routers.sonarr.entrypoints=web
  radarr:
    container_name: radarr
    image: linuxserver/radarr:latest
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${HOME}/Docker/plex/radarr:/config
      - /mnt/zfs/Storage/Media/Movies:/movies
      - /mnt/zfs/Docker/pms/nzbget/downloads/completed/Movies:/downloads/completed/Movies
      - /mnt/zfs/Docker/pms/delugeDownloads:/downloads
      - /mnt/zfs/Docker/pms/delugeDownloads:/data
    labels:
      - traefik.enable=true
      - traefik.http.services.radarr.loadbalancer.server.port=7878
      - traefik.http.routers.radarr.rule=Host(`radarr.hill`)
      - traefik.http.routers.radarr.entrypoints=web

  
networks:
  vpn:
    external:
      name: docker-vpn0